Samsung Analysis
========================================================

Load Library
--------------------------------------------------------
```{r}
library(tree)
library(stringr)
library(randomForest)


```


Processing
--------------------------------------------------------
Download the data & read the data in 

```{r}
setwd("/Users/Carlos/Dropbox/Courses/Data Analysis/Exercices/Data Analysis/Data Analysis 2/code/SamsungAnalysis/")
getwd()
if (!file.exists("../../data/samsungData.rda")){
  download.file("https://spark-public.s3.amazonaws.com/dataanalysis/samsungData.rda", destfile="../../data/samsungData.rda", method = "curl")
  dateDownloaded <- date()
  dateDownloaded
}

load("../../data/samsungData.rda")
```
Munging Data
-------------------------------------------------------------

```{r}
punct <- c("\\(","\\)","\\-","\\,")
for (i in punct){ 
  names(samsungData) <- str_replace_all(names(samsungData),i, "_")
  }
samsungData$activity <- as.factor(samsungData$activity)
samsungData$activityNum <- as.numeric(samsungData$activity)
```
### Look at the data set
```{r}
#head(samsungData)
#summary(samsungData)
#sapply(samsungData[1, ], class)
table(samsungData$activity)
table(mapply(FUN=class, samsungData))
```

### Find out about missing values
```{r}
sum(is.na(samsungData))
```

Prediction
---------------------------------------------------------------
### 1. Find the right data


### 2. Define your error rate 

### 3. Split data into

#### Training
For this analysis the training set must include the data from subjects 1, 3, 5, and 6
```{r}
trainingSet <- samsungData[samsungData$subject == c(1, 3, 5, 6),]

```

#### Testing
The test set is the data from subjects 27, 28, 29, and 30
```{r}
testSet <- samsungData[samsungData$subject == c(27, 28, 29, 30),]

```

```{r fig.width=12, fig.height=6}
for (i in 1:562){
  ##plot(trainingSet[,i], pch=19, col=trainingSet$activityNum, 
  ##   ylab=names(trainingSet)[i])
  print(names(trainingSet)[i])
  boxplot(trainingSet[,i] ~ trainingSet$activity, data=trainingSet, main=names(trainingSet)[i], ylab=names(trainingSet)[i])
}


```

